name: ".NET PR"

permissions:
  contents: read

on:
  workflow_call:

jobs:
  Checks:
    runs-on: 'windows-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Heleonix.Build
        run: nuget install Heleonix.Build -version 6.3.1 -outputdirectory ../hxb
      - name: Validate
        run: dotnet msbuild ../hxb/Heleonix.Build.6.3.1/Main.hxbproj -p:Hx_In_Targets=Hx_NetValidate
      - name: ChangeLog
        run: dotnet msbuild ../hxb/Heleonix.Build.6.3.1/Main.hxbproj -p:Hx_In_Targets=Hx_ChangeLog_GitHubCommit
        env:
            Hx_ChangeLog_GitHubCommit_Token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: dotnet msbuild ../hxb/Heleonix.Build.6.3.1/Main.hxbproj -p:Hx_In_Targets=Hx_NetBuild
#      - name: Test
#        run: dotnet msbuild ../hxb/Heleonix.Build.6.3.1/Main.hxbproj -p:Hx_In_Targets=Hx_OpenCover
#        env:
#            Hx_OpenCover_FilePathReplacement: "https://raw.githubusercontent.com/Heleonix/$1/master/src/"
#            Hx_OpenCover_FilePathRegExp: ".*\\\\([a-zA-Z.]+)\\\\src\\\\"