name: "PR: .NET"

permissions:
  contents: read

on:
  workflow_call:

jobs:
  Validate-Build-Test:
    runs-on: 'windows-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: HxBuild
        run: dotnet tool install Heleonix.Build --version 7.0.0 -g
      - name: Validate
        run: hxbuild -t:Hx_NetValidate
      - name: ChangeLog
        run: hxbuild -t:Hx_ChangeLog_GitHubCommit
        env:
          Hx_ChangeLog_GitHubCommit_Token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: hxbuild -t:Hx_NetBuild
      - name: Test
        run: hxbuild -t:Hx_NetTest