name: "Release: .NET / NuGet"

permissions:
  contents: write

on:
  workflow_call:

jobs:
  Publish-GitRelease-Docs:
    runs-on: 'windows-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: HxBuild
        run: dotnet tool install Heleonix.Build --version 7.0.3 -g
      - name: Validate
        run: hxbuild -t:Hx_NetValidate
      - name: ChangeLog
        run: hxbuild -t:Hx_ChangeLog_GitHubCommit
        env:
          Hx_ChangeLog_GitHubCommit_Token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: hxbuild -t:Hx_NetBuild
      - name: Test
        run: hxbuild -t:Hx_NetTest
      - name: Publish
        run: hxbuild -t:Hx_NetNugetPush
        env:
          Hx_NetNugetPush_SourceURL: "https://www.nuget.org/api/v2/package"
          Hx_NetNugetPush_APIKey: ${{ secrets.NUGET_API_KEY }}
      - name: Release
        run: hxbuild -t:Hx_Release_GitHub
        env:
          Hx_Release_GitHub_Token: ${{ secrets.GITHUB_TOKEN }}
      - name: Docs
        run: hxbuild -t:Hx_DocFX_Git
        env:
          Hx_DocFX_Git_BranchName: "master"
          Hx_DocFX_Git_User: "Heleonix.Build"
          Hx_DocFX_RepositoryUrl: "https://github.com/Heleonix/documentation.git"
          Hx_DocFX_Git_Token: ${{ secrets.HX_DOCS_API }}
